
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALWAYS AP CONJUNCTION DISJUNCTION EVENTUALLY IMPLIES LPAREN NEGATE NEXT RPAREN UNTIL\n    expression :   term DISJUNCTION term\n                 | term CONJUNCTION term\n    \n    expression : term\n    \n    term : ALWAYS factor\n        | EVENTUALLY factor\n        | NEXT factor\n        | NEGATE factor\n    \n       term : term IMPLIES term\n            | term UNTIL term\n            | term DISJUNCTION term\n            | term CONJUNCTION term\n    \n    term : factor\n    \n    factor : AP\n    \n    factor : ALWAYS factor\n           | EVENTUALLY factor\n           | NEXT factor\n           | NEGATE factor\n    \n    factor : LPAREN expression RPAREN\n    '
    
_lr_action_items = {'ALWAYS':([0,3,5,6,7,9,10,11,12,13,14,16,17,18,32,33,],[3,14,14,14,14,3,3,3,3,3,14,14,14,14,3,3,]),'EVENTUALLY':([0,3,5,6,7,9,10,11,12,13,14,16,17,18,32,33,],[5,16,16,16,16,5,5,5,5,5,16,16,16,16,5,5,]),'NEXT':([0,3,5,6,7,9,10,11,12,13,14,16,17,18,32,33,],[6,17,17,17,17,6,6,6,6,6,17,17,17,17,6,6,]),'NEGATE':([0,3,5,6,7,9,10,11,12,13,14,16,17,18,32,33,],[7,18,18,18,18,7,7,7,7,7,18,18,18,18,7,7,]),'AP':([0,3,5,6,7,9,10,11,12,13,14,16,17,18,32,33,],[8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,]),'LPAREN':([0,3,5,6,7,9,10,11,12,13,14,16,17,18,32,33,],[9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,]),'$end':([1,2,4,8,15,19,20,21,23,24,25,26,27,28,29,30,31,34,35,],[0,-3,-12,-13,-4,-5,-6,-7,-1,-2,-8,-9,-14,-15,-16,-17,-18,-10,-11,]),'DISJUNCTION':([2,4,8,15,19,20,21,23,24,25,26,27,28,29,30,31,34,35,],[10,-12,-13,-4,-5,-6,-7,32,32,32,32,-14,-15,-16,-17,-18,32,32,]),'CONJUNCTION':([2,4,8,15,19,20,21,23,24,25,26,27,28,29,30,31,34,35,],[11,-12,-13,-4,-5,-6,-7,33,33,33,33,-14,-15,-16,-17,-18,33,33,]),'RPAREN':([2,4,8,15,19,20,21,22,23,24,25,26,27,28,29,30,31,34,35,],[-3,-12,-13,-4,-5,-6,-7,31,-1,-2,-8,-9,-14,-15,-16,-17,-18,-10,-11,]),'IMPLIES':([2,4,8,15,19,20,21,23,24,25,26,27,28,29,30,31,34,35,],[12,-12,-13,-4,-5,-6,-7,12,12,12,12,-14,-15,-16,-17,-18,12,12,]),'UNTIL':([2,4,8,15,19,20,21,23,24,25,26,27,28,29,30,31,34,35,],[13,-12,-13,-4,-5,-6,-7,13,13,13,13,-14,-15,-16,-17,-18,13,13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,9,],[1,22,]),'term':([0,9,10,11,12,13,32,33,],[2,2,23,24,25,26,34,35,]),'factor':([0,3,5,6,7,9,10,11,12,13,14,16,17,18,32,33,],[4,15,19,20,21,4,4,4,4,4,27,28,29,30,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> term DISJUNCTION term','expression',3,'p_expression','LTL.py',178),
  ('expression -> term CONJUNCTION term','expression',3,'p_expression','LTL.py',179),
  ('expression -> term','expression',1,'p_expression_term','LTL.py',187),
  ('term -> ALWAYS factor','term',2,'p_term','LTL.py',193),
  ('term -> EVENTUALLY factor','term',2,'p_term','LTL.py',194),
  ('term -> NEXT factor','term',2,'p_term','LTL.py',195),
  ('term -> NEGATE factor','term',2,'p_term','LTL.py',196),
  ('term -> term IMPLIES term','term',3,'p_term_binary','LTL.py',202),
  ('term -> term UNTIL term','term',3,'p_term_binary','LTL.py',203),
  ('term -> term DISJUNCTION term','term',3,'p_term_binary','LTL.py',204),
  ('term -> term CONJUNCTION term','term',3,'p_term_binary','LTL.py',205),
  ('term -> factor','term',1,'p_term_factor','LTL.py',211),
  ('factor -> AP','factor',1,'p_factor_name','LTL.py',217),
  ('factor -> ALWAYS factor','factor',2,'p_factor_unary','LTL.py',223),
  ('factor -> EVENTUALLY factor','factor',2,'p_factor_unary','LTL.py',224),
  ('factor -> NEXT factor','factor',2,'p_factor_unary','LTL.py',225),
  ('factor -> NEGATE factor','factor',2,'p_factor_unary','LTL.py',226),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_grouped','LTL.py',233),
]
